name: Build
on:
  push:
    branches: [ ayeshka1 ]

jobs:

#A job to validate gradle wrapper

  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

#A job to gradle linting with JDK 1.8

  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: bash ./gradlew lint

#A job to gradle testing with stacktrace

  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  # A job to gradle build with stacktrace
  build:
      name: gradle build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: gradle build
          run: gradle build --stacktrace