name: Build
on:
  push:
    branches: [ ayeshka1 ]

jobs:

#A job to validate gradle wrapper

  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

#A job to gradle linting with JDK 1.8

  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: bash ./gradlew lint
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results.html

#Locally Devs usually just use ./gradlew lintDebug
#and on CI which happens in the background Devs run the full suite ./gradlew lint

#./gradlew lintDebug  -  run lint with your main sources and debug.
#./gradlew lintRelease -  run lint with your main sources and release.
#./gradlew lint  -  run all of the variations that there are.
#./gradlew lintFlavor1Debug -  run lint with your main sources and the debug sources of flavor1.

#A job to gradle testing with stacktrace

  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html


  # A job to gradle build with stacktrace
  build:
      name: gradle build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: gradle build
          run: gradle build --stacktrace